Revert recreating the encrypted token storage on initialisation error.
schibsted/account-sdk-android-web pull request #61
Opened 2022-11-28 14:23 UTC by zamzterz

If the EncryptedSharedPreferences can't be created, try to delete the existing file and delete the master key.
See https://github.com/google/tink/issues/535 for more info.

This might happen when a user uninstalls an app using this SDK, and then re-installs the app again.

_Follow up of https://github.com/schibsted/account-sdk-android-web/pull/50._

2022-11-28 15:13 UTC, xserxses requested changes
This mechanism caused random logouts during summer 2022 (SDK  2.4.3, 2.4.4) and huge drop of login rate in Schibsted publishers. 

Bringing it back to SDK should be discussed internally.

2022-11-29 09:19 UTC, abdurahmanadilovic commented
> This mechanism caused random logouts during summer 2022 (SDK 2.4.3, 2.4.4) and huge drop of login rate in Schibsted publishers.
> 
> Bringing it back to SDK should be discussed internally.

The alternative is to cause crashes every time the app starts, at least that's what's happening to Podme. So the app becomes unusable until users manually clear app data. Reinstalling the app will still cause the app to crash on start

2022-11-29 09:24 UTC, xserxses commented
If my understanding is correct, disabling backup of Shared Preferences in Android Manifest should mitigate this issue. 

GeneralSecurityException is to wide exception to always log user out. If we'll go with this solution is should be exception specyfic to this case.

2022-11-29 09:26 UTC, abdurahmanadilovic commented
> If my understanding is correct, disabling backup of Shared Preferences in Android Manifest should mitigate this issue.
> 
> GeneralSecurityException is to wide exception to always log user out. If we'll go with this solution is should be exception specyfic to this case.

We tried to set allowBackup=false and it made no difference. We could still recreate the issue by reinstalling the app multiple times

2022-11-29 09:30 UTC, abdurahmanadilovic commented
Another alternative is to stick with nonproblematic version of the Tink library that is throwing the exception

2022-11-29 16:56 UTC, xserxses commented
> Besides, what's the benefit of ignoring this, the encrypted storage can't be recovered anyways?

The problem with propsed soultion is it will log out not only in case You've described but others as well. And based on experience from summer - this is not always non recoverable cases - as GeneralSecurityException covers multiple scenarios.  It should be narrowed down.

In general - we should aim to solve this specyfic case instead of logging people out as default solution...

2023-05-11 07:53 UTC, zamzterz commented
Closing this as work is ongoing to replace the storage backed by `EncryptedSharedPreferences`.

2023-05-11 07:53 UTC, closed without merging