Replace encrypted storage with MigratingSessionStorage
schibsted/account-sdk-android-web pull request #71
Opened 2023-05-12 10:37 UTC by abdurahmanadilovic

# Description 

- Bring back MigratingSessionStorage that will take as an input EncryptedStorage.

2023-05-15 13:16 UTC, zamzterz requested changes
Seems to be working fine 👍

I think the code structure could be clarified, see specific review comment.

2023-05-24 05:55 UTC, abdurahmanadilovic commented on webflows/src/main/java/com/schibsted/account/webflows/persistence/SessionStorage.kt
> +internal class MigratingSessionStorage(
let me know if MigratingSessionStorage looks ok now, it takes in two implementations of SessionStorage now

2023-05-24 05:56 UTC, abdurahmanadilovic commented on webflows/src/main/java/com/schibsted/account/webflows/persistence/SessionStorage.kt
> +        const val PREFERENCE_FILENAME = "SCHACC_TOKENS_SHARED_PREFS"
should not since its a different file name

2023-05-24 12:33 UTC, zamzterz requested changes
Great, thanks for following up on this! 👍 

I think the migration + new sharedprefs storage implementation can be simplified, see specific review commetns.

2023-05-24 12:33 UTC, zamzterz commented on webflows/src/main/java/com/schibsted/account/webflows/persistence/SessionStorage.kt
> +    fun getJsonForClientId(clientId: String): String? = prefs.getString(clientId, null)
As mentioned above, this shouldn't be needed. 🙂

2023-05-24 12:33 UTC, zamzterz commented on webflows/src/main/java/com/schibsted/account/webflows/persistence/SessionStorage.kt
> +            when (newStorage.getJsonForClientId(clientId)) {
This does the same read twice from shared prefs, can't the existing method `get` be used instead? 
Something like (below code also utilises the helper functions on `Either` type):
```kotlin
override fun get(clientId: String, callback: StorageReadCallback) {
    newStorage.get(clientId) { result ->
        result
            .onSuccess { newSession ->
                if (newSession != null) {
                    callback(Either.Right(newSession))
                } else {
                    // if no existing session found, look in previous storage
                    lookupPreviousStorage(clientId, callback)
                }
            }
            .onFailure { lookupPreviousStorage(clientId, callback) }
    }
}

private fun lookupPreviousStorage(clientId: String, callback: StorageReadCallback) {
    previousStorage.get(clientId) { result ->
        result.onSuccess {
            it?.let {
                // migrate existing session
                newStorage.save(it)
                previousStorage.remove(clientId)
            }
        }
        callback(result)
    }
}
```

2023-05-24 12:33 UTC, zamzterz commented on webflows/src/main/java/com/schibsted/account/webflows/persistence/SessionStorage.kt
> +}
Formatting nit: missing newline at end of file.

2023-05-24 12:33 UTC, zamzterz commented on webflows/src/main/java/com/schibsted/account/webflows/util/Util.kt
> +    fun Gson.getStoredUserSession(json: String?): StoredUserSession? {
I think this would be better placed in `SessionStorage.kt` as it's only used there and can be made `private`.

2023-05-24 12:33 UTC, zamzterz commented on webflows/src/main/java/com/schibsted/account/webflows/persistence/SessionStorage.kt
> +        } catch (e: ClassCastException) {
Where can this exception occur? From Gson?

2023-05-24 12:33 UTC, zamzterz commented on webflows/src/main/java/com/schibsted/account/webflows/persistence/SessionStorage.kt
> +internal class MigratingSessionStorage(
Yes, looks great! 👍 I just have some additional comments/questions about implementation details.

2023-05-26 07:32 UTC, abdurahmanadilovic commented on webflows/src/main/java/com/schibsted/account/webflows/persistence/SessionStorage.kt
> +        } catch (e: ClassCastException) {
Its something Shared/EncryptedPreferences can throw in case there is a wrong type. But I am not sure if it's necessary, I'll remove it

2023-06-05 07:05 UTC, bogdan-niculescu-sch reviewed
Overall changes are looking good

2023-06-05 08:41 UTC, bogdan-niculescu-sch approved these changes
Since https://github.com/schibsted/account-sdk-android-web/pull/75 is cloose, approving migration to shared preferences

2023-06-05 11:45 UTC, zamzterz approved these changes
Found tiny last minute thing, which I've pushed a small fix for directly.
After that this looks all good, so will merge and tag a new release including this asap - thanks again for your contribution 🙇 💯 !

2023-06-05 11:45 UTC, zamzterz commented on webflows/src/main/java/com/schibsted/account/webflows/persistence/SessionStorage.kt
> +        null
Upon closer look, I think this should result in a `StorageError` instead:
```kotlin
private fun Gson.getStoredUserSession(json: String?): StorageReadResult {
    return try {
        Either.Right(fromJson(json, StoredUserSession::class.java))
    } catch (e: JsonSyntaxException) {
        Either.Left(StorageError.UnexpectedError(e))
    }
}
```

2023-06-05 12:21 UTC, merged