check for local session before showing login prompt
schibsted/account-sdk-android-web pull request #97
Opened 2023-09-29 10:41 UTC by bogdan-niculescu-sch

2023-09-29 10:44 UTC, bogdan-niculescu-sch commented on webflows/src/main/java/com/schibsted/account/webflows/client/Client.kt
> +        var internalSessionFound = true
kindof messy using variable for `sessionStorage.get`, but couldn't call `userHasSessionOnDevice` under `.onFailure` because it is a suspension function

2023-09-29 12:23 UTC, xserxses requested changes

2023-09-29 12:23 UTC, xserxses commented on webflows/src/main/java/com/schibsted/account/webflows/client/Client.kt
> +        sessionStorage.get(configuration.clientId) { result ->
Actually it's quite ugly.
You kinda assume that "get" will happen in one thread and there will be no async operations there and as result  onSuccess/onFailure will be called before this thread will move to if statement. 

When I look on sessionStorage implementation - this should work (there is no async operations there) but it's a potentially error prone in the future.

I think we should wrap this callback API in suspendig courutine - check https://github.schibsted.io/smp-distribution/android-hermes-app/blob/master/library-ui-app-review/src/main/kotlin/com/schibsted/publishing/review/AppReview.kt#L85

2023-10-02 13:14 UTC, xserxses approved these changes

2023-10-02 13:18 UTC, merged